### ISSUE TITLE
Lock file for live streams do not have unique names

### ISSUE THREAD

**Issue by LeMarcDomar** [Brisppy/twitch-archiver#10]
**Describe the bug**
Unlike VOD lock files, live stream lock files do not have unique names. As a result, whenever live stream lock files are not discarded correctly, all live streams from that streamer from that point on will fail to get archived, always returning the "Lock file present for stream by [name], skipping." message.

**Supplied arguments**
python3 ./twitch-archiver.py -c CHANNEL_NAME -t 4 -d "PATH/TWITCH-ARCHIVER/" -w --stream-only

**Comment by Brisppy** [comment]
This should be fixed on the develop branch with 25224c9f09f89aa5b3ea51daa82ca5a97696c330, stream lock files now use the format `.lock.stream_id-stream-only`.
