### ISSUE TITLE
Question about custom Exception implementation

### ISSUE THREAD

**Issue by HeliosLHC** [Brisppy/twitch-archiver#16]
Hi @Brisppy,

I'm looking through some of the exceptions in exceptions.py and noticed that the following format is used for custom exceptions.

```python
class ChatExportError(Exception):
    def __init__(self, error):
        self.message = f'Chat export failed. Error: {error}'
```

From looking at the code, nothing appears (please correct me if I'm wrong) to read the "message" attribute of these custom exceptions nor are these messages printed out console output when the custom exceptions are raised. The custom formatted strings in the exceptions don't appear to be used or output.

The "message" attribute for exceptions appear to be [deprecated](https://peps.python.org/pep-0352/#retracted-ideas) in Python 3.0.

Does there happen to be an intended use for the "message" attribute in the custom exception?

**Comment by Brisppy** [comment]
I'm not too familiar with how to properly implement custom exceptions so this is just what I went with because it worked - The 'message' attribute is included in the traceback so I was just using it to give some sort of understandable output on an exception.

```
Traceback (most recent call last):
  File "/opt/twitch-archiver/src/processing.py", line 202, in get_vod_connector
    raise VodMergeError('VOD length outside of acceptable range. If error persists delete '
src.exceptions.VodMergeError: VOD length outside of acceptable range. If error persists delete 'vod/parts' directory if VOD still available.
```

If there's a better way of doing this I'm open to suggestions.

**Comment by HeliosLHC** [comment]
Thanks for clarification, this syntax perhaps may be better suited instead:
```python
class CustomException(Exception):
    "Raised when a certain event occurs"
    def __init__(self, arg1, arg2):
        
        message = f"formatted message here: {arg1} {arg2}"
        super().__init__(message)
```
