### ISSUE TITLE
Concurrent mass chat log downloads from multiple VODs 

### ISSUE THREAD

**Issue by Goosegit11** [Brisppy/twitch-archiver#22]
**Is your feature request related to a problem? Please describe.**

Need to download chat logs from many VODs. Current one-by-one downloads are very slow. 

**Describe the solution you'd like**

Allow parallel downloads - multiple chat log downloads running simultaneously across threads.

**Describe alternatives you've considered** 

None, only option is slow one-by-one downloads.

**Describe how this feature would help YOU meet your archiving goals**

Would speed up downloading many chat logs for my archives.

**Describe how this feature would help OTHERS meet their archiving goals**

Faster mass chat log downloads for anyone archiving lots of VODs. 

**Additional context**

https://github.com/Daniele122898/TwitchMassChatDownloader

That guy implemented it in his program, but it's old, non-configurable and looks kinda abandoned.

**Comment by Brisppy** [comment]
Thanks for the suggestion.
Should be pretty simple as long as you're fine with it being mutually exclusive with video archiving. I'll add an argument for enabling a bulk chat archiving mode over the weekend.

**Comment by Brisppy** [comment]
Pushed an update to the [develop branch](https://github.com/Brisppy/twitch-archiver/tree/develop) which will bulk any chat logs if you run with just the `-C`  or `--chat` flag. Let me know if you run into any issues.

**Comment by Goosegit11** [comment]
Can you elaborate on what you did and how it works? 
Do I feed some .txt with VOD IDs into it or what?

Thanks!

**Comment by Brisppy** [comment]
Sure. You will need to open up the dev branch [here](https://github.com/Brisppy/twitch-archiver/tree/develop) and follow the manual installation instructions to install the newest build.

Then if you run twitch-archiver with the `-C` or `--chat` flag along with a channel it will parallelize the chat downloads.

Bulking without supplying a channel isn't implemented - I'll look into that when I do a refactor in the near future along with being able to supply VOD IDs from a file.

**Comment by Goosegit11** [comment]
Oh, you see, I have a list with IDs from which I need to get the chat logs. Not the whole channel. Can this be implemented?

**Comment by Brisppy** [comment]
Ahh I see, if you don't mind waiting a week or two I should have the next version in testing which will include a way to grab VODs from a file. Will update here when it's ready.

**Comment by Brisppy** [comment]
Sorry for the long wait, I've just put out the first (and hopefully only) [release candidate build](https://github.com/Brisppy/twitch-archiver/releases/tag/v4.0.0.rc1) for v4.0.0.

Along with a total refactor, you can now add the `--file` flag along with `--channel` or `--vod` to interpret the provided variable(s) as a file path to import from. The file should have one VOD ID or channel on each line.

e.g `twitch-archiver -v /var/vods.txt --file`

**Comment by Goosegit11** [comment]
Error:

```
twitch-archiver -v 42748720
2024-01-23 22:36:59 [    INFO] Twitch Archiver v4.0.3 - https://github.com/Brisppy/twitch-archiver
2024-01-23 22:37:01 [    INFO] 1 VOD(s) in download queue.
2024-01-23 22:37:02 [   ERROR] Exception occurred inside DownloadHandler. ['  File "/home/user/twitch-archiver/second/lib/python3.11/site-packages/twitcharchiver/processing.py", line 274, in _start_download\n    _downloader.start()\n', '  File "/home/user/twitch-archiver/second/lib/python3.11/site-packages/twitcharchiver/downloaders/video.py", line 203, in start\n    raise VideoDownloadError(exc) from exc\n']
2024-01-23 22:37:02 [   ERROR] Error archiving VOD {'vod_id': '42748720', 'stream_id': 0, 'title': 'Reckful - 3v3 with chanimals/sodah - twitter.com/ByronBernstein for updates', 'description': 'highlighting so
it doesn&#39;t get deleted  ', 'created_at': datetime.datetime(2014, 8, 17, 19, 43, 8), 'published_at': datetime.datetime(2014, 8, 17, 19, 43, 8, 290499), 'thumbnail_url': 'https://static-cdn.jtvnw.net/cf_vods/d2nvs31859zcd8/2ffb112a6c/reckful_5894588416_5894588416/thumb/thumb0-90x60.jpg', 'duration': 17838, 'chat_archived': False, 'video_archived': False}.
Traceback (most recent call last):
  File "/home/user/twitch-archiver/second/lib/python3.11/site-packages/twitcharchiver/downloaders/video.py", line 150, in start
    self._base_url = self._extract_base_url(self._index_url)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/twitch-archiver/second/lib/python3.11/site-packages/twitcharchiver/downloaders/video.py", line 256, in _extract_base_url
    _m = re.findall(r"(?<=\/)(index.*)", index_url)[0]
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/twitch-archiver/second/lib/python3.11/site-packages/twitcharchiver/processing.py", line 274, in _start_download
    _downloader.start()
  File "/home/user/twitch-archiver/second/lib/python3.11/site-packages/twitcharchiver/downloaders/video.py", line 203, in start
    raise VideoDownloadError(exc) from exc
twitcharchiver.exceptions.VideoDownloadError: list index out of range


```

**Comment by Brisppy** [comment]
So the issue with this VOD is it's a `highlight` rather than a direct archive of a VOD. I'll see about adding support for downloading these if possible, though they won't be batch downloaded from a channel like VODs currently are.
