### ISSUE TITLE
If a title contains multibyte characters, they are replaced with "_"

### ISSUE THREAD

**Issue by NoodlesStamps** [Brisppy/twitch-archiver#23]
**Describe the bug**
```
 twitch-archiver  --archive-only --chat -v 1959912263 -d /content/chats2
2023-10-27 19:14:21 [ WARNING] New version of Twitch-Archiver available - Version 3.0.7:
https://github.com/Brisppy/twitch-archiver/releases/latest
Release notes:

**(2023-08-31) Version 3.0.7**
**Changes and Fixes:**
 * Increased the start delay for newly live channels.

2023-10-27 19:14:21 [    INFO] OAuth token verified successfully. Expiring in 887521
2023-10-27 19:14:21 [    INFO] Now processing VOD: 1959912263
2023-10-27 19:14:22 [    INFO] VOD offline.
2023-10-27 19:14:22 [    INFO] Grabbing chat logs...
2023-10-27 19:14:23 [    INFO] Found 199 messages. 28716  -  ETA: 00:00:01
```

```
cd C:\content\chats2
(base) PS C:\content\chats2> ls


: C:\content\chats2


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        2023/10/27     19:14                2023-10-25_12-36-35 - lol____ - 1959912263


```

**Operating system**
Your operating system (Windows, Linux, Mac)
Windows10 and Ubuntu(WSL2)

This program is very useful for archiving, thank you for making this!

**Comment by Brisppy** [comment]
Thanks for opening an issue - This is intended behaviour (currently).

Depending on the file system there's a number of reserved or blacklisted characters which cannot be used in a file name or path, but could be used in the title of a Twitch VOD. There's quite a lot of [discussion](https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names) around this and solutions, but the way I went about this is just to replace everything except numbers, letters and spaces with an underscore. The original title is still available inside the `vod.json` file though which should be saved with the VOD.

I'll look into changing this though with v4.0.0 as it isn't ideal and makes titles for non-english streams entirely unreadable.

**Comment by NoodlesStamps** [comment]
I see that was the intended behavior, and I'm sorry I asked the question without understanding it.
Thank you for reply !

**Comment by Brisppy** [comment]
No worries, knowing that people care enough to open issues / PRs inspires me to keep working on and improving the project.
I've been meaning to revisit file naming at some point anyway, in the next release everything except for a couple symbols (thanks to windows) will be allowed in the title.
