### ISSUE TITLE
Question about playing downloaded content

### ISSUE THREAD

**Issue by schibunaki** [Brisppy/twitch-archiver#28]
Hi. This tool is really amazing. But how do I play it like on twitch? I mean, how do i display the video and also have the chat like in the twitch player? Its really great that this tool also downloads the chat log as txt, but with what software/player can I actually watch the VODs with the chat like on twitch?

**Comment by Brisppy** [comment]
Hi thanks for the interest in the project, unfortunately I don't have a solution for this currently, the primary purpose of this program is hands-off archival. There are [some projects](https://github.com/lay295/TwitchDownloader) out there which may be more suited for your purposes.
