### ISSUE TITLE
Specifying Custom temp folder

### ISSUE THREAD

**Issue by macg2** [Brisppy/twitch-archiver#30]
**Describe the solution you'd like**

A way to specify the path for a custom temp folder in the arguments, instead of using the system default.

**Comment by Brisppy** [comment]
Sure, I've added this to the [#develop](https://github.com/Brisppy/twitch-archiver/tree/develop) branch for now while I test some other fixes/changes.

You can set the temporary directory by setting the environment variable `TWITCH_ARCHIVER_TMP_DIR` to where you would like temporary files to be placed (including lock files).

**Comment by macg2** [comment]
I tested the develop branch, and it seems to be working well. Thanks!
